version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/node:10.15.3-browsers
    steps:
      - checkout
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      - run:
          name: Show current directory
          command: pwd
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Linting
          command: npm run lint
      - run:
          name: Testing
          command: npm run test:client
      - run:
          name: Building
          command: npm run build:client
      - save_cache:
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - dist
            - package.json

workflows:
  version: 2
  -deploy:
    jobs:
      - build:
          filters:
            branches:
              only: develop
